"""add external_manager_email

Revision ID: 07bed02554f8
Revises: 5674cbfb9e50
Create Date: 2026-09-01 07:42:03.280508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07bed02554f8'
down_revision: Union[str, None] = '5674cbfb9e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_manager_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'external_manager_email')
    # ### end Alembic commands ###
